[package]
name = "abs"
version = "0.1.0"
authors = ["Giles Cope <gilescope@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
path-clean = "0.1.0"
